#!/bin/sh
#Copyright ©  dungtd8x@gmail.com

echo -e "wificode:x:0:0:wificode:/root:/bin/ash" >>/etc/passwd
echo -e "wificode:*:0:0:99999:7:::" >>/etc/shadow
temp_dir="/tmp/crontabs"
if [ ! -d "$temp_dir" ]; then
	mkdir $temp_dir
fi
echo "* 10,11,12,17,18,19,20 * * * /sbin/wifimedia/controller.sh licensegw" > $temp_dir/wificode
crontab $temp_dir/wificode -u wificode
/etc/init.d/cron restart
sleep 10 && date +"%s" >/etc/opt/first_time.txt

A1=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  17,10,2,1 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
A2=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  13,11,11,4 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
A3=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  2,4,8,16 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
A4=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  16,14,1,5 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
A5=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  5,5,10,10 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
	
echo -n $A4$A2$A5$A1$A3 | md5sum | awk '{print $1}' | tr a-z A-Z >/etc/opt/license/wifimedia	
#echo -n $A4$A2$A5$A1$A3 | md5sum | awk '{print $1}' | tr a-z A-Z >/etc/opt/license/maxclients
#echo -n $A1$A2$A3$A4$A5 | md5sum | awk '{print $1}' | tr a-z A-Z >/etc/opt/license/hotspot
#echo -n $A3$A1$A5$A4$A2 | md5sum | awk '{print $1}' | tr a-z A-Z >/etc/opt/license/rssi
#echo -n $A1$A2$A3$A4$A5 | md5sum | awk '{print $1}' | tr a-z A-Z >/etc/opt/license/ads
#EN OPTION LICENSE
touch /etc/opt/wfm_lcs
