#!/bin/sh

rnd=`cat /dev/urandom | tr -dc 'A-Z' | head -c1`
###For RAMMIT
uci -q get wifimedia.@sync[0] || {
	uci batch <<-EOF
	add wifimedia sync
	set wifimedia.@sync[0]=sync
	set wifimedia.@sync[0].domain="crm.wifimedia.vn"
	commit wifimedia
EOF
}

uci batch <<-EOF
	set system.@system[0]=system
	set system.@system[0].hostname="WIFIMEDIA.VN"
	set system.@system[0].zonename='Asia/Ho Chi Minh'
	set system.@system[0].timezone=ICT-7
EOF

uci batch <<-EOF
	set network.lan.ipaddr=192.168.5.1
	set network.wan.type=bridge
	commit network
EOF

uci batch <<-EOF
	set wireless.@wifi-iface[0].maxassoc=30
	set wireless.@wifi-iface[0].ssid=OPENWIFI
	#set wireless.@wifi-iface[0].ssid=PDA_$rnd
	#set wireless.@wifi-iface[0].encryption="mixed-psk"
    	#set wireless.@wifi-iface[0].key="123456A@$rnd"
	commit wireless
EOF

#Add vitual SSID
#For abng
uci -q get wireless.@wifi-iface[1] || {
        uci batch <<EOF
        add wireless wifi-iface
        set wireless.@wifi-iface[1].device=radio0
        set wireless.@wifi-iface[1].mode=ap
        set wireless.@wifi-iface[1].network=lan
        set wireless.@wifi-iface[1].ssid=OPENWIFIx2
	set wireless.@wifi-iface[1].disabled=1
        commit wireless
EOF
}


uci batch <<-EOF
#	set wireless.@wifi-device[0].channel=36
	set wireless.@wifi-device[-1].channel=6
#	set wireless.@wifi-device[0].disabled=0
#	set wireless.@wifi-device[-1].disabled=0
#XIAOMI
#	set wireless.@wifi-iface[0].ssid=OPENWIFI-5GHz
#	set wireless.@wifi-iface[1].ssid=OPENWIFI-2.4GHz
	set wireless.@wifi-device[-1].macaddr=$(cat /sys/class/ieee80211/phy0/macaddress)
	add_list wireless.radio0.ht_capab="SHORT-GI-20"
	add_list wireless.radio0.ht_capab="SHORT-GI-40"
	add_list wireless.radio0.ht_capab="RX-STBC1"
	add_list wireless.radio0.ht_capab="DSSS_CCK-40"
	set wireless.radio0.country="TW"
	commit wireless
EOF
#enable wifi
uci set wireless.radio0.disabled="0"
uci commit wireless
wifi
#for hwmode n ac
uci batch <<-EOF
	delete network.wan6
	commit network
EOF

uci batch <<-EOF
	set firewall.@zone[1].input="ACCEPT"
	commit firewall
	EOF
#Password	
echo -e "admin:x:1000:1000:admin:/root:/bin/false" >>/etc/passwd
echo -e "admin:*:0:0:99999:7:::" >>/etc/shadow
echo -e "admin\nadmin" | passwd admin

echo -e "wifimedia:x:0:0:wifimedia:/root:/bin/ash" >>/etc/passwd
echo -e "wifimedia:*:0:0:99999:7:::" >>/etc/shadow
echo -e "09465670089\n09465670089" | passwd wifimedia

#Change password for root
word=$(cat /sys/class/ieee80211/phy0/macaddress | cut -c  10,11,13,14,16,17 | sed 's/://g' |awk '{print $1}'|tr a-z A-Z)
pwd=$(echo -n $word | md5sum | awk '{print $1}')
echo -e "admin\nadmin" | passwd root
#End

#Info
CODENAME="WIFIMEDIA"
if [ -f "/etc/codename" ]; then
	source /etc/codename
fi
uci batch <<-EOF
	delete wifimedia.Version
	set wifimedia.Version=version
	set wifimedia.Version.ver=$CODENAME
	commit wifimedia
EOF
source /etc/openwrt_release
rm -f /etc/openwrt_release
DISTRIB_DESCRIPTION=$(uci get wifimedia.Version.ver)" v3.1a"
echo 'DISTRIB_ID="'"$DISTRIB_ID"'"' >> /etc/openwrt_release
echo 'DISTRIB_RELEASE="'"$DISTRIB_RELEASE"'"' >> /etc/openwrt_release
echo 'DISTRIB_REVISION="'"$DISTRIB_REVISION"'"' >> /etc/openwrt_release
echo 'DISTRIB_CODENAME="'"$DISTRIB_CODENAME"'"' >> /etc/openwrt_release
echo 'DISTRIB_TARGET="'"$DISTRIB_TARGET"'"' >> /etc/openwrt_release
echo 'DISTRIB_DESCRIPTION="'"$DISTRIB_DESCRIPTION"'"' >> /etc/openwrt_release

rm -f /etc/privoxy/default.action
rm -f /etc/privoxy/default.filter

#chmod a+x /sbin/wifimedia/*.sh

######Cron job
echo "*/1 * * * * /sbin/wifimedia/clear.sh" >>/etc/crontabs/root
/etc/init.d/cron start
/etc/init.d/cron enable

uci set dhcp.lan.start=10
uci set dhcp.lan.leasetime=1h

uci commit dhcp
#SYNCH TIME
uci batch <<-EOF
	del system.ntp
	set system.ntp=timeserver
        add_list system.ntp.server='0.asia.pool.ntp.org'
        add_list system.ntp.server='1.asia.pool.ntp.org'
        add_list system.ntp.server='2.asia.pool.ntp.org'
        add_list system.ntp.server='3.asia.pool.ntp.org'
	set system.ntp.enabled=1
	set system.ntp.enable_server=1
	commit system
EOF

##LED XIAOMI-MIWIFI
#uci batch <<-EOF
#	set system.led_power.name='power'
#	set system.led_power.default='1'
#	set system.led_power.trigger='netdev'
#	set system.led_power.dev='br-wan'
#	set system.led_power.mode='link tx rx'
#	set system.led_power.sysfs='xiaomi:blue:status'
#	commit system
#EOF
uci set luci.diag.dns="google.com.vn"
uci set luci.diag.ping="google.com.vn"
uci set luci.diag.route="google.com.vn"

#Change ssh
uci batch <<-EOF
	set dropbear.@dropbear[0].Port=2702
	commit dropbear
EOF
touch /etc/opt/wfm_status
/etc/init.d/dropbear restart
/etc/init.d/system reload
/etc/init.d/led reload
sleep 5
/etc/init.d/network restart
sleep 5 && rm -f /etc/uci-defaults/wifimedia