#!/bin/sh
touch /etc/config/arpbind

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@arpbind[-1]
	add ucitrack arpbind
	set ucitrack.@arpbind[-1].init=arpbind
	delete arpbind.@arpbind[-1]
	add arpbind arpbind
	set arpbind.@arpbind[0]=arpbind
	commit arpbind
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
