#!/bin/sh /etc/rc.common

START=99
STOP=15

EXTRA_COMMANDS="status"
EXTRA_HELP="        status  checking"

boot() {
    sleep 10 && /sbin/wifimedia/upgrade.sh
    sleep 10 && /sbin/wifimedia/licensekey.sh
    /sbin/wifimedia/groups.sh
    /sbin/wifimedia/gpconfig.sh
}
