#!/bin/sh /etc/rc.common

START=99
STOP=15

EXTRA_COMMANDS="status"
EXTRA_HELP="        status  checking"

boot() {
    sleep 10 && /sbin/wifimedia/controller_srv.sh upgrade_srv
	sleep 10 && /sbin/wifimedia/controller.sh license_srv
}
