#!/bin/sh

#/etc/init.d/nodogsplash disable
echo -e "nds:x:0:0:nds:/root:/bin/ash" >>/etc/passwd
#write file crontabs
_nds=/etc/cron_nds
echo '*/5 * * * * /sbin/wifimedia/heartbeat.sh' >$_nds
echo ''>/etc/crontabs/nds && /etc/init.d/cron restart
NET_ID="nextify"
FW_ZONE="nextify"
IFNAME="nextify0.1" #VLAN1
domain=`uci -q get wifimedia.@nodogsplash[0].domain`
domain_default=${domain:-portal.nextify.vn/splash}
MAC_E0=$(ifconfig eth1 | grep 'HWaddr' | awk '{ print $5 }')
#write file splash
#write file splash
echo '<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>$gatewayname</title>
  </head>
  <body>
      <form id="info" method="POST" action="//'$domain_default'">
          <input type="hidden" name="gateway_name" value="$gatewayname">
          <input type="hidden" name="gateway_mac" value="'$MAC_E0'">
          <input type="hidden" name="client_mac" value="$clientmac">
          <input type="hidden" name="num_clients" value="$nclients">
          <input type="hidden" name="uptime" value="$uptime">
          <input type="hidden" name="auth_target" value="$authtarget">
      </form>
      <script>
          document.getElementById("info").submit();
      </script>
  </body>
</html>' >/etc/nodogsplash/htdocs/splash.html

#write file infoskel
echo '<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Whoops...</title>
        <meta http-equiv="refresh" content="0; url="//'$domain'">
        <style>
            html {
                background: #F7F7F7;
            }
        </style>
    </head>
    <body></body>
</html>' >/etc/nodogsplash/htdocs/status.html


uci -q get wifimedia.@nodogsplash[0] || {
        uci batch <<EOF
        add wifimedia nodogsplash
		set wifimedia.@nodogsplash[0].domain="portal.nextify.vn/splash"
		set wifimedia.@nodogsplash[0].https=0
        commit wifimedia
EOF
}

uci batch << EOF
	set network.${NET_ID}=interface
	set network.${NET_ID}.ifname=${IFNAME}
	set network.${NET_ID}.proto=static
	set network.${NET_ID}.type=bridge
	set network.${NET_ID}.ipaddr=10.68.255.1
	set network.${NET_ID}.netmask=255.255.255.0
	set dhcp.${NET_ID}=dhcp
	set dhcp.${NET_ID}.interface=${NET_ID}
	set dhcp.${NET_ID}.start=100
	set dhcp.${NET_ID}.leasetime=1h
	set dhcp.${NET_ID}.limit=150
	set firewall.${FW_ZONE}=zone
	set firewall.${FW_ZONE}.name=${FW_ZONE}
	set firewall.${FW_ZONE}.network=${NET_ID}
	set firewall.${FW_ZONE}.forward=REJECT
	set firewall.${FW_ZONE}.output=ACCEPT
	set firewall.${FW_ZONE}.input=REJECT 
	set firewall.${FW_ZONE}_fwd=forwarding
	set firewall.${FW_ZONE}_fwd.src=${FW_ZONE}
	set firewall.${FW_ZONE}_fwd.dest=wan
	set firewall.${FW_ZONE}_dhcp=rule
	set firewall.${FW_ZONE}_dhcp.name=${FW_ZONE}_DHCP
	set firewall.${FW_ZONE}_dhcp.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dhcp.target=ACCEPT
	set firewall.${FW_ZONE}_dhcp.proto=udp
	set firewall.${FW_ZONE}_dhcp.dest_port=67-68
	set firewall.${FW_ZONE}_dns=rule
	set firewall.${FW_ZONE}_dns.name=${FW_ZONE}_DNS
	set firewall.${FW_ZONE}_dns.src=${FW_ZONE}
	set firewall.${FW_ZONE}_dns.target=ACCEPT
	set firewall.${FW_ZONE}_dns.proto=tcpudp
	set firewall.${FW_ZONE}_dns.dest_port=53
	set dhcp.${NET_ID}.force=1
	set dhcp.${NET_ID}.netmask=255.255.255.0
	add_list dhcp.${NET_ID}.dhcp_option=6,8.8.8.8,8.8.4.4
	commit
EOF

/etc/init.d/nodogsplash disable
uci set nodogsplash.@nodogsplash[0].enabled='0'
uci set nodogsplash.@nodogsplash[0].gatewayinterface="br-nextify";
uci add_list nodogsplash.@nodogsplash[0].users_to_router="allow all"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 172.16.99.1"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 125.212.224.252"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 171.244.6.33"
uci add_list nodogsplash.@nodogsplash[0].preauthenticated_users="allow to 103.104.116.6"
uci commit nodogsplash
/etc/init.d/nodogsplash stop
uci commit network
uci commit dhcp
uci commit firewall
/etc/init.d/network restart
/etc/init.d/dnsmasq restart
/etc/init.d/firewall restart


