#!/bin/sh /etc/rc.common

START=6
STOP=15

lcs=/etc/opt/wfm_lcs

boot() {
	if [ -e "$lcs" ];then
			/sbin/wifimedia/controller.sh license_srv >/dev/null 2>&1
	fi
	
	# Wait for network up & running
	while true; do
    	ping -c1 -W1 8.8.8.8
    	if [ ${?} -eq 0 ]; then
      	  	break
   	else
        	sleep 1
    	fi
	done
	/sbin/wifimedia/controller.sh checking
	/sbin/wifimedia/controller.sh action_lan_wlan
}
