#!/bin/sh /etc/rc.common

START=99
STOP=15

EXTRA_COMMANDS="status"
EXTRA_HELP="        status  checking"
lcs=/etc/opt/wfm_lcs
model_hardware=$(cat /proc/cpuinfo | grep 'machine' | cut -f2 -d ":" | cut -b 10-50 | tr ' ' '_')
#dnsctl=$(uci -q get meshdesk.internet1.dns)
#ip=`nslookup $dnsctl | grep 'Address' | grep -v '127.0.0.1' | grep -v '8.8.8.8' | grep -v '0.0.0.0'|grep -v '::' | awk '{print $3}'`
#if [ "$ip" != "" ] &&  [ -e /etc/config/meshdesk ];then
#	uci set meshdesk.internet1.ip=$ip
#	uci commit meshdesk
#fi
	
#echo $ip
boot() {
    #sleep 10 && /sbin/wifimedia/controller_srv.sh upgrade_srv && /sbin/wifimedia/updates.sh && /sbin/wifimedia/preauthenticated_rules.sh >/dev/null 2>&1
	
	if [ -e "$lcs" ];then
		if [ "$model_hardware" == "TL-WR840N_v6" ] || [ "$model_hardware" == "TL-WR841N_v14" ]; then
			/sbin/wifimedia/controller.sh lgw_srv >/dev/null 2>&1
		else 
			/sbin/wifimedia/controller.sh license_srv >/dev/null 2>&1
		fi
	fi
	
	if [ -e /etc/config/meshdesk ];then
		sbin/wifimedia/controller.sh meshdesk >/dev/null 2>&1
	fi
	
}
